// Mocks generated by Mockito 5.0.7 from annotations
// in mockito_test/test/widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito_test/model/freezed_model.dart' as _i2;
import 'package:mockito_test/service/service.dart' as _i3;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeFreezedModel extends _i1.Fake implements _i2.FreezedModel {}

/// A class which mocks [SampleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSampleService extends _i1.Mock implements _i3.SampleService {
  MockSampleService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FreezedModel giveModel() =>
      (super.noSuchMethod(Invocation.method(#giveModel, []),
          returnValue: _FakeFreezedModel()) as _i2.FreezedModel);
  @override
  _i4.Future<List<dynamic>> getUsers() =>
      (super.noSuchMethod(Invocation.method(#getUsers, []),
              returnValue: Future<List<dynamic>>.value(<dynamic>[]))
          as _i4.Future<List<dynamic>>);
  @override
  void saveUser(dynamic user) =>
      super.noSuchMethod(Invocation.method(#saveUser, [user]),
          returnValueForMissingStub: null);
}
